sudo: false

language: perl

install:
  - yes | perlbrew install-cpanm
  - cpanm --notest https://gitlab.com/cpran/CPrAN.git
  - cpran init
  - cpran update

before_script:
  - cpran deps | cpran install --notest -
  - cpran upgrade
  - mkdir -p $HOME/.local/bin
  - cpran install praat:6.0.28 --barren --yes --path $HOME/.local/bin
  - ls -l $HOME/.local/bin
  - cpran --version
  - echo $PATH

script:
  - cpran test
  
cache:
  directories:
  - $PERLBREW_ROOT
  - $HOME/.praat-dir
