sudo: false

language: perl

addons:
  apt:
    packages:
    - praat

install:
  - yes | perlbrew install-cpanm
  - cpanm --notest https://gitlab.com/cpran/CPrAN.git
  - cpran init
  - cpran update

before_script:
  - cpran deps | cpran install --notest --reinstall -
  - mkdir -p $HOME/.local/bin
  - cpran install praat:6.0.28 --barren --yes --path $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - cpran --version

script:
  - cpran test
  
cache:
  directories:
  - $PERLBREW_ROOT
  - $HOME/.praat-dir
