sudo: false

language: perl

install:
  - cpanm -v https://gitlab.com/cpran/CPrAN.git
  - cpran init
  - cpran update

before_script:
  - cpran deps | cpran --notest --reinstall install
  - mkdir -p $HOME/.local/bin
  - cpran install praat --path $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - cpran --version

script:
  - cpran test
  
cache:
  directories:
  - $HOME/.praat-dir
